# Generated by Django 4.1 on 2022-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studybud', '0004_user_followers_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures'),
        ),
    ]
